# Zapat Issue Template — Bug Report
# Copy to .github/ISSUE_TEMPLATE/bug-report.yml in your repo.
# The "agent" label is pre-applied so Zapat triages automatically.

name: Bug Report
description: Report a bug for Zapat to triage and fix
labels: ["agent", "bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly. Include steps to reproduce if possible.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Logs, screenshots, environment details, or anything else that helps.
    validations:
      required: false
